services:
  app:
    image: ghcr.io/msahes00/sw2-goaldraft:latest
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    environment:
      PORT: ${PORT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      LOCALTUNNEL_SUBDOMAIN: ${LOCALTUNNEL_SUBDOMAIN}
      LOCALTUNNEL_ENABLED: ${LOCALTUNNEL_ENABLED}

    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: ${DB_PORT}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - db:/var/lib/mysql

volumes:
  db: