# This workflow will build and push the Docker image to GitHub Container Registry
name: Build and push to ghcr.io

# Trigger the workflow manually, on push or tag creation
# It will only triger on the main branch
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'


# Build and push the Docker image
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Add the .gitignore contents to the .dockerignore
        run: cat .gitignore >> .dockerignore

      - name: Set up QEMU for multiarch support
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}:latest